[project]
name = "hds-capstone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "notebook>=7.4.3",
    "pandas>=2.3.0",
    "pymupdf>=1.26.0",
    "scikit-learn>=1.6.1",
]
